### ISSUE TITLE
bash.exe: warning: could not find /tmp, please create!

### ISSUE THREAD

**Issue by orschiro** [sheabunge/GitPortable#6]
I get this error when pulling from a repo:
```
$ git pull
bash.exe: warning: could not find /tmp, please create!
```
Any ideas how to fix this?

Robert

**Comment by ramiroalvarez** [comment]
Open Start Menu

Type "cmd"

Press Enter

type "bash"

Press Enter

type "mkdir /tmp"

Press Enter

Close the command prompt window

Solved the error for me

**Comment by bungeshea** [comment]
@axgdev Thanks, I can reproduce the error now.

@ramiroalvarez That does indeed solve the error - the only issue now is removing the need to run those commands.

**Comment by blokeley** [comment]
@ramiroalvarez 
1. I tried "cmd; bash" and got "bash is not a recognised... command"
2. If I try "mkdir /tmp" in the git bash window, it says "/tmp already exists"

**Comment by qq42** [comment]
I worked around this issue by adding the following to my ~/.bash_profile:

    [ ! -d /tmp ] && mkdir /tmp

Adding this to the /etc/profile script will fix it for everyone.

I discovered that `mkdir /tmp` "magically" from within msysgit creates the directory in the user's temp directory, i.e. on Windows 7 when it creates `/tmp`, `/tmp` actually maps to `%USERPROFILE%\AppData\Local\Temp\GitPortableTemp`.

**Comment by sheabunge** [comment]
@qq42 great idea on adding the creation code to the profile script; I've done so and will build 1.9.5 Dev Test 2 shortly. Could everyone please try it out and see if this issue is resolved.

**Comment by sheabunge** [comment]
This should be fixed in [1.9.5 Development Test 2](https://github.com/sheabunge/GitPortable/releases/download/v1.9.5-devtest.2/GitPortable_1.9.5_Development_Test_2_online.paf.exe). Could people please test it out and report back here.

**Comment by Orobas** [comment]
I just downloaded and installed 1.9.5 Development Test 2 from the link on Github, the error still occurred for me.

**Comment by Murmur** [comment]
I tried .bash_profile fix but did not work, but found an interesting behaviour.
```
Run GitPortable.exe
$ ls -la /tmp          ## tmp dir is found
$ cd /c/projects
$ ls -la /tmp       ## tmp dir is not found gitk does gives a warning
$ mkdir /tmp
$ ls -la /tmp       ## tmp dir is found and gitk does not give a warning
```
Tried to put `cd /c/ && mkdir /tmp` in a .bash_profile but but I think it does not want to chdir to /C/* folders

**Comment by 19379** [comment]
Rather than running GitPortable.exe, navigate to the **App\Git** folder and run **git-bash.bat**. Doing that has solved my tmp folder errors.

**Comment by Murmur** [comment]
This did the \app\git\git-bash.bat script opens a console where /tmp folder stays alive. Problem solved.

**Comment by sheabunge** [comment]
Git for Windows proper has been released, and includes new ways to launch Git Bash or Git Cmd. I'll be updating Git Portable soon to use the new version; hopefully that should fix this bug.

**Comment by sheabunge** [comment]
I've released [Git Portable 2.5.1 Dev Test 1](https://github.com/sheabunge/GitPortable/releases/download/v2.5.1-devtest.1/GitPortable_2.5.1_Development_Test_1.paf.exe), which updates Git to version 2.5.1 and uses a completely new launcher system which should fix this issue.

**Comment by qq42** [comment]
When running Git Bash Portable right after the upgrade/install for `Git Portable 2.5.1 Dev Test 1` completes it says:
`Failed to fork child process: Resource temporarily unavailable.
DLL rebasing may be required. See 'rebaseall --help'.`

![image](https://cloud.githubusercontent.com/assets/12665801/9697126/e10fa6e4-534e-11e5-90d3-9930e603308b.png)

**Comment by adica** [comment]
@ramiroalvarez  solution works for me as well.
thanks!

**Comment by sheabunge** [comment]
I've just released a new version which uses Git 2.5.3. @qq42 @adica

**Comment by jwalker009** [comment]
@ramiroalvarez solution works for me as well, except I opened the command window from git bash

**Comment by raszpl** [comment]
GitPortable_2.6.2_Development_Test_1.paf = bash.exe: warning: could not find /tmp, please create!

**Comment by sheabunge** [comment]
I'm closing this issue for now; if this error occurs in a new version please create a new one.
